INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (1, 4, '2026-06-07', 'Pending');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (2, 3, '2026-05-13', 'Pending');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (3, 6, '2025-12-25', 'Delivered');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (4, 1, '2026-04-16', 'Pending');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (5, 3, '2026-06-06', 'Delivered');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (6, 11, '2025-09-10', 'Cancelled');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (7, 8, '2026-02-09', 'Shipped');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (8, 1, '2026-04-23', 'Shipped');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (9, 2, '2025-11-24', 'Cancelled');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (10, 5, '2026-06-13', 'Shipped');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (11, 11, '2025-09-08', 'Delivered');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (12, 3, '2026-03-01', 'Pending');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (13, 14, '2026-07-22', 'Shipped');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (14, 11, '2025-12-10', 'Pending');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (15, 6, '2025-11-01', 'Shipped');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (16, 4, '2026-04-27', 'Pending');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (17, 10, '2025-12-29', 'Pending');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (18, 11, '2026-05-30', 'Pending');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (19, 5, '2026-07-27', 'Shipped');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (20, 4, '2026-03-20', 'Delivered');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (21, 4, '2026-07-06', 'Pending');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (22, 8, '2026-01-05', 'Cancelled');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (23, 10, '2025-12-27', 'Shipped');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (24, 6, '2026-01-31', 'Shipped');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (25, 4, '2026-03-26', 'Pending');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (26, 15, '2026-02-21', 'Cancelled');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (27, 4, '2025-11-25', 'Delivered');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (28, 8, '2026-04-03', 'Shipped');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (29, 10, '2026-05-11', 'Delivered');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (30, 2, '2025-09-26', 'Pending');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (31, 9, '2026-04-25', 'Delivered');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (32, 13, '2026-03-25', 'Cancelled');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (33, 10, '2026-01-01', 'Shipped');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (34, 8, '2026-03-19', 'Pending');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (35, 13, '2026-04-05', 'Delivered');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (36, 13, '2026-03-14', 'Cancelled');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (37, 2, '2026-02-15', 'Cancelled');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (38, 3, '2026-07-25', 'Shipped');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (39, 13, '2025-08-23', 'Shipped');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (40, 4, '2026-01-03', 'Shipped');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (41, 10, '2026-03-20', 'Delivered');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (42, 14, '2026-04-18', 'Delivered');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (43, 1, '2026-04-04', 'Pending');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (44, 4, '2025-09-29', 'Shipped');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (45, 6, '2025-11-07', 'Pending');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (46, 4, '2025-08-08', 'Pending');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (47, 6, '2025-10-25', 'Cancelled');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (48, 2, '2026-01-31', 'Delivered');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (49, 4, '2026-06-14', 'Cancelled');
INSERT INTO orders (order_id, customer_id, order_date, status) VALUES (50, 2, '2025-08-09', 'Delivered');

INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (1, 1, 8, 3, 142.46);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (2, 1, 9, 5, 15.98);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (3, 1, 8, 5, 114.04);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (4, 1, 6, 5, 193.26);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (5, 2, 8, 5, 13.53);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (6, 2, 10, 4, 11.46);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (7, 2, 7, 3, 101.45);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (8, 2, 8, 4, 140.22);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (9, 3, 1, 4, 39.06);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (10, 3, 10, 4, 184.19);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (11, 3, 6, 3, 139.24);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (12, 3, 9, 1, 52.54);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (13, 4, 10, 3, 41.53);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (14, 4, 10, 5, 41.03);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (15, 4, 9, 2, 115.66);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (16, 4, 7, 2, 188.9);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (17, 5, 9, 3, 72.12);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (18, 6, 1, 4, 9.84);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (19, 7, 7, 3, 104.6);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (20, 7, 1, 4, 146.42);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (21, 7, 2, 5, 165.51);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (22, 8, 6, 4, 52.84);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (23, 8, 9, 4, 95.84);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (24, 9, 1, 4, 19.8);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (25, 10, 6, 4, 99.05);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (26, 10, 8, 2, 152.45);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (27, 11, 8, 2, 16.11);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (28, 11, 8, 3, 118.35);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (29, 11, 8, 1, 42.41);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (30, 12, 4, 3, 113.8);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (31, 13, 9, 1, 88.12);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (32, 13, 8, 4, 151.82);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (33, 13, 9, 1, 51.02);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (34, 14, 10, 3, 94.69);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (35, 14, 4, 5, 127.13);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (36, 14, 7, 2, 32.37);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (37, 14, 1, 1, 127.92);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (38, 15, 9, 5, 43.6);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (39, 15, 9, 1, 88.01);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (40, 16, 8, 1, 183.57);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (41, 16, 10, 2, 90.88);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (42, 16, 8, 4, 123.01);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (43, 17, 2, 1, 89.0);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (44, 18, 8, 2, 40.61);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (45, 18, 1, 2, 43.58);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (46, 18, 6, 2, 194.0);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (47, 19, 6, 4, 88.95);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (48, 19, 8, 1, 97.55);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (49, 19, 2, 1, 6.58);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (50, 20, 1, 3, 6.22);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (51, 20, 10, 4, 52.36);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (52, 20, 9, 4, 94.16);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (53, 21, 3, 3, 69.19);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (54, 21, 9, 1, 63.26);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (55, 21, 2, 5, 194.11);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (56, 21, 9, 3, 90.35);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (57, 22, 2, 3, 163.07);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (58, 22, 8, 4, 11.39);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (59, 22, 9, 1, 97.42);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (60, 22, 5, 1, 12.2);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (61, 23, 5, 4, 190.76);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (62, 23, 7, 2, 180.74);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (63, 23, 7, 4, 108.01);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (64, 23, 5, 4, 160.17);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (65, 24, 5, 5, 65.72);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (66, 25, 3, 1, 30.3);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (67, 26, 7, 4, 140.91);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (68, 26, 8, 3, 140.79);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (69, 27, 8, 1, 194.45);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (70, 27, 3, 1, 189.18);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (71, 28, 8, 3, 134.06);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (72, 29, 6, 3, 112.17);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (73, 30, 2, 4, 57.63);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (74, 31, 9, 5, 198.75);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (75, 31, 10, 3, 89.95);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (76, 31, 8, 5, 29.77);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (77, 31, 9, 3, 181.98);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (78, 32, 9, 3, 118.95);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (79, 32, 6, 5, 21.23);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (80, 32, 2, 1, 186.39);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (81, 33, 3, 1, 46.49);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (82, 33, 8, 5, 30.11);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (83, 34, 1, 1, 141.93);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (84, 34, 2, 2, 76.94);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (85, 34, 1, 2, 71.36);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (86, 35, 5, 1, 50.83);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (87, 35, 3, 5, 147.04);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (88, 35, 9, 4, 168.92);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (89, 35, 9, 2, 24.34);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (90, 36, 9, 3, 140.9);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (91, 36, 4, 1, 187.28);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (92, 36, 3, 3, 174.42);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (93, 37, 7, 5, 126.2);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (94, 37, 3, 2, 124.82);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (95, 37, 1, 1, 197.9);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (96, 37, 3, 2, 93.3);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (97, 38, 5, 3, 35.3);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (98, 39, 8, 3, 111.81);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (99, 40, 8, 3, 56.91);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (100, 40, 4, 3, 15.89);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (101, 41, 10, 5, 21.77);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (102, 41, 4, 4, 21.51);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (103, 41, 1, 5, 131.99);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (104, 42, 10, 2, 8.71);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (105, 42, 6, 4, 73.58);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (106, 42, 2, 4, 43.9);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (107, 43, 2, 3, 147.78);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (108, 44, 4, 4, 162.48);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (109, 45, 7, 2, 79.27);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (110, 45, 10, 1, 70.09);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (111, 45, 4, 3, 90.43);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (112, 46, 6, 1, 194.85);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (113, 46, 4, 2, 27.16);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (114, 46, 7, 4, 196.69);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (115, 47, 3, 1, 141.97);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (116, 47, 4, 5, 165.57);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (117, 48, 6, 5, 145.7);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (118, 48, 5, 1, 180.42);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (119, 48, 1, 2, 45.4);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (120, 49, 2, 2, 163.62);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (121, 50, 1, 1, 130.07);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (122, 50, 3, 1, 165.2);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (123, 50, 10, 5, 53.79);
INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_at_purchase) VALUES (124, 50, 8, 2, 22.15);